
# Initialize the datasource with available DDL and DML scripts
# spring.sql.init.mode=always
# spring.jpa.defer-datasource-initialization= true

server.port = 8080

spring.datasource.url=jdbc:postgresql://localhost:5432/blogapi

spring.datasource.username=blogapi
spring.datasource.password=password

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
management.endpoints.web.exposure.include=*
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

spring.flyway.clean-on-validation-error=true
spring.flyway.clean-disabled=false
flyway.clean.disable=false

app.jwt-secret=daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
app-jwt-expiration-milliseconds=604800000